"""Add UserSettings and BlockedUser models

This migration adds two new tables:
- user_settings: Stores user preferences for matching, privacy, notifications, gaming, and social settings
- blocked_users: Manages blocked user relationships

Revision ID: ed9b4ddb180b
Revises: 1765069941
Create Date: 2025-12-06 16:13:31.436368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed9b4ddb180b'
down_revision = '1765069941'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blocked_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blocker_id', sa.Integer(), nullable=False),
    sa.Column('blocked_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['blocked_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['blocker_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('min_age_preference', sa.Integer(), nullable=True),
    sa.Column('max_age_preference', sa.Integer(), nullable=True),
    sa.Column('gender_preference', sa.String(length=30), nullable=True),
    sa.Column('language_preference', sa.String(length=200), nullable=True),
    sa.Column('gaming_preference', sa.String(length=200), nullable=True),
    sa.Column('min_hours_played', sa.Integer(), nullable=True),
    sa.Column('only_common_games', sa.Boolean(), nullable=False),
    sa.Column('discovery_enabled', sa.Boolean(), nullable=False),
    sa.Column('profile_visible', sa.Boolean(), nullable=False),
    sa.Column('show_age', sa.Boolean(), nullable=False),
    sa.Column('show_location', sa.Boolean(), nullable=False),
    sa.Column('show_hours_played', sa.Boolean(), nullable=False),
    sa.Column('show_steam_id', sa.Boolean(), nullable=False),
    sa.Column('show_discord', sa.Boolean(), nullable=False),
    sa.Column('searchable', sa.Boolean(), nullable=False),
    sa.Column('email_match_notifications', sa.Boolean(), nullable=False),
    sa.Column('email_like_notifications', sa.Boolean(), nullable=False),
    sa.Column('email_review_notifications', sa.Boolean(), nullable=False),
    sa.Column('email_weekly_summary', sa.Boolean(), nullable=False),
    sa.Column('app_sound_notifications', sa.Boolean(), nullable=False),
    sa.Column('app_push_notifications', sa.Boolean(), nullable=False),
    sa.Column('steam_sync_enabled', sa.Boolean(), nullable=False),
    sa.Column('steam_sync_frequency', sa.String(length=20), nullable=True),
    sa.Column('show_steam_library', sa.Boolean(), nullable=False),
    sa.Column('chat_from_matches_only', sa.Boolean(), nullable=False),
    sa.Column('read_receipts_enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_settings')
    op.drop_table('blocked_users')
    # ### end Alembic commands ###
